import { ReplaySessionSchema } from '../f1.schemas';

// Generated by the data service's real replay builder from its synthetic
// test race (DataService/tests/fake_session.py), so this spec fails if the
// two services drift apart. Regenerate after changing the replay model.
import fixture from './replay-session.fixture.json';
import { toReplaySessionDto } from './replay-session.dto';

describe('ReplaySessionSchema', () => {
  it('accepts a payload produced by the data service', () => {
    expect(ReplaySessionSchema.safeParse(fixture).success).toBe(true);
  });

  it('rejects a replay without a sample interval', () => {
    const withoutInterval: Record<string, unknown> = { ...fixture };
    delete withoutInterval.sampleInterval;

    expect(ReplaySessionSchema.safeParse(withoutInterval).success).toBe(false);
  });
});

describe('toReplaySessionDto', () => {
  it('maps to camelCase and keeps the per-sample columns aligned', () => {
    const dto = toReplaySessionDto(ReplaySessionSchema.parse(fixture));
    const samples = dto.drivers[0]?.progress.length ?? 0;

    expect(dto.roundNumber).toBe(14);
    expect(samples).toBeGreaterThan(0);
    expect(
      dto.drivers.every(
        (driver) =>
          driver.status.length === samples && driver.gap.length === samples,
      ),
    ).toBe(true);
  });
});
